# --- IDENTIFICATION ---
sonar.projectKey=Mart1n-S_GiveAWay
sonar.organization=mart1n-s
sonar.sourceEncoding=UTF-8

# --- SOURCES À ANALYSER ---
# On cible précisément les dossiers de code source
sonar.sources=apps/mobile/src,apps/mobile/app,apps/api/src,packages/shared/src

# --- EXCLUSIONS (Ce qu'on ignore) ---
# 1. Dossiers techniques (node_modules, build, coverage, android/ios natifs)
# 2. Fichiers de tests (*.spec.ts, *.test.ts)
# 3. Fichiers de config et JSON (*.json, *.js, *.mjs, *.map) pour éviter les faux positifs sur les fichiers de config
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/android/**,**/ios/**,**/.expo/**,**/*.spec.ts,**/*.test.ts,**/*.e2e.ts,**/*.json,**/*.js,**/*.mjs,**/*.map

# --- COUVERTURE DE TESTS ---
# 1. On indique les chemins vers les fichiers LCOV générés en local/CI
sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info,packages/shared/coverage/lcov.info

sonar.coverage.exclusions=apps/mobile/**/*
# Pour l'instant, on exclut toute la couverture
# sonar.coverage.exclusions=**/*

# --- TYPESCRIPT ---
sonar.typescript.tsconfigPath=tsconfig.json