# sonar-project.properties

# Clé unique du projet (trouvée sur SonarCloud)
sonar.projectKey=Mart1n-S_GiveAWay
# Ton organisation (généralement ton pseudo GitHub en minuscule ou tel qu'affiché sur Sonar)
sonar.organization=mart1n-s

# Encodage
sonar.sourceEncoding=UTF-8

# Dossiers à analyser (On inclut mobile, api, et les packages)
sonar.sources=apps/mobile,apps/api/src,packages/ui/src,packages/shared/dist

# Exclusions (ce qu'on ne veut PAS analyser)
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**,**/android/**,**/ios/**,**/*.json

# Tests (Optionnel pour l'instant)
# sonar.tests=apps/api/test