server {
    listen 80;
    server_name _;
    index index.html;

    # Assets statiques (JS/CSS/images) servis depuis client/
    location /_expo/ {
        root /usr/share/nginx/html/client;
        try_files $uri =404;
    }

    location /assets/ {
        root /usr/share/nginx/html/client;
        try_files $uri =404;
    }

    location = /favicon.ico {
        root /usr/share/nginx/html/client;
        try_files $uri =404;
    }

    # Pages HTML servies depuis server/
    location / {
        root /usr/share/nginx/html/server;
        try_files $uri $uri/ /index.html;
    }

    # Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}