export enum AdminRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
}

export enum AdminLogAction {
  // EPIC 1
  VALIDATE_ASSOCIATION = "VALIDATE_ASSOCIATION",
  REJECT_ASSOCIATION = "REJECT_ASSOCIATION",
  SUSPEND_ASSOCIATION = "SUSPEND_ASSOCIATION",
  REACTIVATE_ASSOCIATION = "REACTIVATE_ASSOCIATION",
  REQUEST_DOCUMENTS = "REQUEST_DOCUMENTS",
  // EPIC 2
  CREATE_USER = "CREATE_USER",
  UPDATE_USER = "UPDATE_USER",
  SUSPEND_USER = "SUSPEND_USER",
  REACTIVATE_USER = "REACTIVATE_USER",
  RESET_USER_PASSWORD = "RESET_USER_PASSWORD",
  DELETE_USER = "DELETE_USER",
  // EPIC 3
  CREATE_ASSOCIATION = "CREATE_ASSOCIATION",
  UPDATE_ASSOCIATION = "UPDATE_ASSOCIATION",
  DELETE_ASSOCIATION = "DELETE_ASSOCIATION",
  // EPIC 5
  CREATE_ADMIN = "CREATE_ADMIN",
  UPDATE_ADMIN = "UPDATE_ADMIN",
  RESET_ADMIN_PASSWORD = "RESET_ADMIN_PASSWORD",
  DELETE_ADMIN = "DELETE_ADMIN",
}

export type AdminLogEntityType = "USER" | "ASSOCIATION" | "MISSION" | "ADMIN";
